<?php
/**
* Webkul Software
*
* @category  Webkul
* @package   DigitalHub_Juno
* @author    Webkul
* @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
* @license   https://store.webkul.com/license.html
*/
$_helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
?>
<nav class="wk-mp-menu wk-mp-main">
    <ul id="wk-mp-nav">
        <?php
        if ($isPartner){ ?>
        <li class="nav item notification-link level-0 <?php echo strpos($magentoCurrentUrl,'digitalhub_juno/seller/config')? "current active":"";?>">
            <a href="<?php echo $block->getUrl('digitalhub_juno/seller/config', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                <?php /* @escapeNotVerified */ echo __('Juno') ?>
            </a>
        </li>
        <?php } ?>
    </ul>
</nav>
